services:
  - type: web
    name: nafas-chest-xray
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 120 app:app
    plan: free
